# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
# source 'https://gitlab.com/hotmob-sdk/ios-sdk.git'


target 'HotmobPreloadDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HotmobiOSSDKDemo
  pod 'HotmobiOSSDK', :path => '../../../hotmob-ios-sdk'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'ObjectMapper', '~> 4.2'
  pod 'SwiftyJSON'
  pod 'SWRevealViewController', '2.3.0'
  pod 'RxWebKit', '~> 2.0'

  target 'HotmobPreloadDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HotmobPreloadDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
