# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'
# source 'https://gitlab.com/hotmob-sdk/ios-sdk.git'


target 'HotmobiOSSDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HotmobiOSSDKDemo
  pod 'HotmobiOSSDK', :path => '../../hotmob-ios-sdk'
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'ObjectMapper', '~> 4.2'
  pod 'SwiftyJSON'
  pod 'SWRevealViewController', '2.3.0'
  pod 'RxWebKit', '~> 2.0'
  pod 'Google-Mobile-Ads-SDK', '~> 10.10.0'

  target 'HotmobiOSSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'HotmobiOSSDK', :path => '../../hotmob-ios-sdk'

  end

  target 'HotmobiOSSDKDemoUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'HotmobiOSSDK', :path => '../../hotmob-ios-sdk'

  end

end
